In [10]:
x = [1,2,3,4]
y = [5,6,7,8]

In [11]:
x*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [12]:
x+10

TypeError: can only concatenate list (not "int") to list

In [13]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
import numpy as np

In [15]:
ax = np.array(x)

In [16]:
ay = np.array(y)

In [17]:
ax*2

array([2, 4, 6, 8])

In [18]:
ax+10

array([11, 12, 13, 14])

In [19]:
ax +ay

array([ 6,  8, 10, 12])

In [20]:
def f(x):
    return 3*x**2 - 2*x +7

f(ax)

array([ 8, 15, 28, 47])

- 对整个数组中所有元素同时执行数学运算可以使得作用在整个数组上的函数运算简单而又快速

In [21]:
np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [22]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [23]:
grid = np.zeros(shape=(10000,10000), dtype=float)

In [24]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
grid +=10

In [26]:
grid

array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])

In [27]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ...,
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

In [28]:
grid

array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])

- 关于 NumPy 有一点需要特别的主意，那就是它扩展 Python 列表的索引功能

In [29]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
a[1]

array([5, 6, 7, 8])

In [31]:
# 选一列
a[:,1]

array([ 2,  6, 10])

In [32]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
a[1:3, 1:3] += 10

In [34]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [35]:
a + [100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 117, 119, 111],
       [109, 121, 123, 115]])

In [36]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [37]:
# 条件赋值
np.where(a<10,a,10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])